export enum TipoEmpresa {
  INDIVIDUAL,
  LTDA,
  SOCIEDADE_ANONIMA,
  OUTRAS_ENTIDADES_EMPRESARIAIS,
  ADMINISTRACAO_PUBLICA,
  ENTIDADES_SEM_FINS_LUCRATIVOS,
  ORGANIZACOES_INTERNACIONAIS_OUTRAS_INSTITUICOES_EXTRATERRITORIAIS,
  COOPERATIVA,
  MICRO_EMPREENDEDOR_INDIVIDUAL_MEI,
  EMPRESA_INDIVIDUAL_RESPONSABILIDADE_LIMITADA_EIRELI,
}
