export enum TipoOrgao {
  LICENCA_FUNCIONAMENTO = 'LICENCA_FUNCIONAMENTO',
  HORARIO_ESPECIAL = 'HORARIO_ESPECIAL',
  BOMBEIROS = 'BOMBEIROS',
  VIGILANCIA = 'VIGILANCIA',
  AMBIENTAL = 'AMBIENTAL',
  ANP = 'ANP',
  USO_SOLO = 'USO_SOLO',
  CETESB = 'CETESB',
  JUCESP = 'JUCESP',
  OUTROS = 'OUTROS'
}
