export enum ClassificacaoRiscoAssociado {
  ISENTO = 'ISENTO',
  BAIXO_RISCO_A = 'BAIXO_RISCO_A',
  BAIXO_RISCO_B = 'BAIXO_RISCO_B',
  ALTO = 'ALTO',
  ALTO_PERGUNTAS = 'ALTO_PERGUNTAS',
  NAO_DEFINIDO = 'NAO_DEFINIDO',
  MEDIO_RISCO = 'MEDIO_RISCO',
  ALTO_RISCO = 'ALTO_RISCO'
}
