export enum ExigibilidadeIss {
  EXIGIVEL = 'EXIGIVEL',
  NAOINCIDENCIA = 'NAOINCIDENCIA',
  ISENCAO = 'ISENCAO',
  EXPORTACAO = 'EXPORTACAO',
  IMUNIDADE = 'IMUNIDADE',
  EXIBILIDADESUSPENSADJ = 'EXIBILIDADESUSPENSADJ',
  EXIBILIDADESUSPENSAPA = 'EXIBILIDADESUSPENSAPA'
}
