export enum PessoaType {
  FISICA,
  JURIDICA,
  ESTRANGEIRA
}

export enum PessoaStatus {
  ATIVO,
  INATIVO,
  EXCLUIDO
}

export enum PessoaSexoType {
  MASCULINO,
  FEMININO
}

export enum PessoaEstadoCivil {
  SOLTEIRO,
  CASADO,
  DIVORCIADO,
  VIUVO,
  UNIAO_ESTAVEL,
  LEGALMENTE_SEPARADO
}

export enum PessoaEscolaridade {
  SEM_INSTRUCAO,
  FUNDAMENTAL_INCOMPLETO,
  FUNDAMENTAL_COMPLETO,
  MEDIO_INCOMPLETO,
  MEDIO_COMPLETO,
  SUPERIOR_INCOMPLETO,
  SUPERIOR_COMPLETO,
  POS_GRADUACAO_INCOMPLETO,
  POS_GRADUACAO_COMPLETO,
  MESTRADO_INCOMPLETO,
  MESTRADO_COMPLETO,
  DOUTORADO_INCOMPLETO,
  DOUTORADO_COMPLETO,
  NAO_ALFABETIZADO
}

export enum PessoaFuncao {
  NENHUM,
  FUNCIONARIO_PUBLICO,
  AGENTE_POLITICO,
  AGENTE_PUBLICO
}

export enum PessoaSanguineoType {
  A,
  B,
  AB,
  O
}

export enum PessoaFatorSanguineoType {
  POSITIVO,
  NEGATIVO
}

export enum PessoaCutis {
  BRANCA,
  PRETA,
  AMARELA,
  INDIGENA,
  PARDA,
  NAO_DECLARADA,
}

export enum PessoaJuridicaType {
  EMPRESA_INDIVIDUAL,
  SOCIEDADE_LIMITADA,
  SOCIEDADE_ANONIMA,
  OUTRAS_ENTIDADES_EMPRESARIAIS,
  ADMINISTRACAO_PUBLICA,
  ENTIDADES_SEM_FINS_LUCRATIVOS,
  ORGANIZACAO_NAO_GOVERNAMENTAL,
  COOPERATIVA,
  MEI,
  EIRELI
}

export enum PessoaContatoType {
  TELEFONE_RESIDENCIAL,
  EMAIL,
  TELEFONE_CELULAR,
  TELEFONE_COMERCIAL,
  SKYPE
}

export enum PessoaGenero {
  FEMININO,
  MASCULINO,
  TRANSGENERO
}

export enum PessoaOrientacaoSexual {
  HETEROSSEXUAL,
  HOMOSSEXUAL,
  BISSEXUAL,
  NAO_INFORMADO
}

export enum PessoaRelacionamento {
  PAI,
  MAE,
  FILHO,
  SOCIO,
  CONJUGE
}
