export enum RegimeEspecialTributacao {
  NAOPOSSUI = 'NAOPOSSUI',
  MICROEMPRESAMUNICIPAL = 'MICROEMPRESAMUNICIPAL',
  ESTIMATIVA = 'ESTIMATIVA',
  SOCIEDADEPROFISSIONAIS = 'SOCIEDADEPROFISSIONAIS',
  COOPERATIVA = 'COOPERATIVA',
  MEI = 'MEI',
  MEEPP = 'MEEPP',
  EMPRESAPEQUENOPORTE = 'EMPRESAPEQUENOPORTE'
}
