export enum SituacaoMobiliarioSia7 {
  ATIVO = '01 - Ativo',
  SUSPENSO = '02 - Suspenso',
  BAIXADO = '03 - Baixado',
  INATIVO = '04 - Inativo',
  TEMPO_DETERMINADO = '05 - Tempo Determinado',
  PUBLICO = '06 - Público',
  BAIXA_OMISSAO = '07 - Baixa Omissão',
  CANCELADO = '08 - Cancelado',
  PARALISADA = '09 - Paralisada',
  BAIXADA_EXOFICIO = '10 - Baixada Ex-Oficio',
  INATIVA_EXOFICIO = '11 - Inativa Ex-Oficio',
  SUSPENSO_EXOFICIO = '12 - Suspenso Ex-Oficio',
  ATIVO_PROVISORIO = '13 - Ativo Provisório',
  ATIVO_IRREGULAR = '14 - Ativo Irregular',
  INDEFERIDO = '15 - Indeferido',
  PROCESSO_ABERTURA = '16 - Em Processo de Abertura',
  PROCESSO_ALTERACAO = '17 - Em processo de Alteração',
  PROCESSO_PARALIZACAO = '18 - Em Processo de Paralização Temporária',
  PROCESSO_BAIXA = '19 - Em Processo de Baixa',
  EXCLUSAO_LOGICA = '99 - Exclusão Lógica',
}
