export enum SituacaoAnaliseEndereco {
  PROTOCOLADA = 'PROTOCOLADA' ,
  EM_ESTUDO = 'EM_ESTUDO',
  DEFERIDA = 'DEFERIDA',
  INDEFERIDA = 'INDEFERIDA',
  CANCELADA_PELA_PREFEITURA = 'CANCELADA_PELA_PREFEITURA',
  CANCELADA_PELO_USUARIO = 'CANCELADA_PELO_USUARIO',
  EM_REESTUDO = 'EM_REESTUDO',
  SUJEITA_ANALISE_ESPECIFICA = 'SUJEITA_ANALISE_ESPECIFICA',
  APROVADO_COM_RESTRICAO = 'APROVADO_COM_RESTRICAO'
}
