export enum StatusSolicitacao {
  ANALISE = 'ANALISE',
  ANDAMENTO = 'ANDAMENTO',
  DEFERIDA = 'DEFERIDA',
  INDEFERIDA = 'INDEFERIDA',
  CONCLUIDA = 'CONCLUIDA',
  CANCELADA = 'CANCELADA',
  SUSPENSA = 'SUSPENSA',
  EMITIDA = 'EMITIDA',
  EXCLUIDA = 'EXCLUIDA',
  EXIGENCIA = 'EXIGENCIA',
  REVOGADO = 'REVOGADO',
}
